/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotbot

class Bot {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(Bot().greeting)
}
